//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.RecFBs = new HashSet<RecFB>();
        }
    
        public int MemberId { get; set; }

        [Display(Name = "Email")]
        public string MemberName { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Sur Name")]
        public string SurName { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime DateOfBirth { get; set; }

        [Required]
        [Display(Name = "Street No")]
        public string StreetNo { get; set; }

        [Required]
        [Display(Name = "Street Name")]
        public string StreetName { get; set; }

        [Required]
        [Display(Name = "Suburb")]
        public string Suburb { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Zip Code")]
        public string ZipCode { get; set; }

        [Required]
        [Display(Name = "Phone")]
        public string PhoneNo { get; set; }

        [Required]
        [Display(Name = "How did you know us?")]
        public string KnowWay { get; set; }

        [Required]
        [Display(Name = "How would you like us to contact you?")]
        public string ContactWay { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime LastLogin { get; set; }
        public int CancelFlg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecFB> RecFBs { get; set; }
    }
}
