//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; }

        [Required]
        [Display(Name = "Category Name")]
        public int CategoryNo { get; set; }

        [Required]
        [Display(Name = "Discription")]
        public string Discription { get; set; }

        [Display(Name = "Picture")]
        public string Picture { get; set; }

        [Required]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Required]
        [Display(Name = "In Stock Quantity")]
        public int InStock { get; set; }

        [Required]
        [Display(Name = "Price")]
        public decimal Price { get; set; }

        [Required]
        [Display(Name = "Member Price")]
        public decimal MemberPrice { get; set; }

        [Required]
        [Display(Name = "Weight")]
        public decimal Weight { get; set; }

        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int CancelFlg { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
